---
title: "このブログ作ったときのメモ"
author: "naruse"
date: '2021-02-10'
categories:
  - R
tags:
  - blogdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE)
```

# R blogdown

Rでいろいろちまちま実行することが多いので簡単に（本当に簡単に）メモできる環境が欲しかったので作成。 環境構築時のコードをメモ。

```{r cars ,eval=FALSE}
# blogdownのインストール
devtools::install_github('rstudio/blogdown')

# hugoのインストール
library(blogdown)
blogdown::install_hugo()
```

# Including Plots

なおRmarkdownでコードを実行するかどうかは次の通り。:

```{r pie, fig.cap='A fancy pie chart.', tidy=FALSE , eval=FALSE}
include	#コードと結果を表示しない
echo	#コードを表示しない
message	#メッセージを表示しない
eval	#コードを実行しない
```

プロジェクトを作成した後↓

```{r new, eval=FALSE}

#最初に
new_site()

#これはちょっと古いっぽい
new_site(theme="alanorth/hugo-theme-bootstrap4-blog")

#このブログはこれ
new_site(theme="vaga/hugo-theme-m10c")

# 編集内容を反映し統合
build_site()
# 反映内容を確認
serve_site()

#こういうのも必要らしいがまだやってない
publishDir = "docs"
hasCJKLanguage = true

#これも未使用
new_content("post/newContent.Rmd")

```

notepadいらねえなこれ。

記事追加する時や編集するときはpublicじゃなくてcontentのほうを編集するっぽい。

で、Knitしてpush。

pushするときにチェックつけていくんだがTool→Shellで「git add -A」と打てばおｋ。

アドインでNew postを使ったときは出来上がりの.Rmdのタイトルとかに""がつかないので注意。
